group 'shtrihjavapos'

apply plugin: 'java'
apply plugin: 'idea'

clean.doFirst {
    delete "${projectDir}/../dist/zip/javase"
    delete "${projectDir}/build/"
}

sourceSets {
    main {
        java {
            srcDirs = [ "src" ]
        }
        resources {
            srcDirs = [ "${projectDir}/src/" ]
            includes = [ "res/*.*", "**/resources/*.*" ]
        }
    }
}

repositories {
    flatDir {
        dirs "${projectDir}/../lib"
    }
}

dependencies {
    implementation 'javapos:javapos:1.14.2'
    implementation 'xerces:xercesImpl:2.12.2'
    implementation 'log4j-api:log4j-api:2.25.1'
    implementation 'log4j-core:log4j-core:2.25.1'
    implementation 'nrjavaserial:nrjavaserial:3.9.3'

    testImplementation 'org.hamcrest:hamcrest-core:1.3'
    testImplementation 'junit:junit:4.12'
}

task utilVersionClass() {
    def clazz = new File("${projectDir}/src/com/bsmart/util/ServiceVersion.java")
    clazz.text = "package com.bsmart.util;\n\npublic class ServiceVersion {\n    public static final String VERSION = \""+version+"\";\n}"
}

jar {
    archiveFileName = "smscale.jar"
    manifest {
        attributes(
            "Implementation-Title": "BSmart.JavaPOS",
            "Class-Path": configurations.compileClasspath.collect { it.getName() }.join(' '),
            "Implementation-Version": version
        )
    }
}
jar.dependsOn('utilVersionClass')

task dist(type: Zip) {
    destinationDirectory = file("${rootDir}/../dist/zip/javase/")
    archiveBaseName = 'bsmart-jpos-scale'
    dependsOn jar
    
    from jar.archiveFile
    from configurations.compileClasspath
    from "Res/"
    from "${rootDir}/../History.txt"
    from "${rootDir}/../Doc/JposScaleDriver.txt"
}

artifacts {
   archives dist
}